version: '3.8'
services:
    mongodb:
        container_name: mongodb
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=password
            - MONGO_INITDB_ROOT_PASSWORD=username
            - MONGO_INITDB_DATABASE=admin
        volumes:
            - ./data:/data/db
        command: mongod --port 27017
        ports:
            - "27017:27017"
        networks:
            - default

    node-api:
       container_name: node-api
       build:
           context: .
           dockerfile: Dockerfile
       depends_on:
           - mongodb
       volumes:
          # - /app/node_modules
          - .:/app
       env_file: .env
       ports:
           - "4000:4000"
       networks:
            - default

networks:
    default:
        external: true
        name: dansmultipro
